name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 go build -tags static -o tcproxy_linux_amd64 -ldflags "-X ./Version=${{ github.ref }}" .
        GOOS=linux GOARCH=arm64 go build -tags static -o tcproxy_linux_arm64 -ldflags "-X ./Version=${{ github.ref }}" .
        GOOS=darwin GOARCH=amd64 go build -tags static -o tcproxy_darwin_amd64 -ldflags "-X ./Version=${{ github.ref }}" .
    - name: Create release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload release asset (linux-amd64)
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./tcproxy_linux_amd64
        asset_name: tcproxy_linux_amd64
        asset_content_type: binary/octet-stream
    - name: Upload release asset (linux-arm64)
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./tcproxy_linux_arm64
        asset_name: tcproxy_linux_arm64
        asset_content_type: binary/octet-stream
    - name: Upload release asset (darwin-amd64)
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./tcproxy_darwin_amd64
        asset_name: tcproxy_darwin_amd64
        asset_content_type: binary/octet-stream
